      <nav class="py-2 mb-2" aria-label="breadcrumb">
        <div class="d-none d-md-block d-lg-block">
          <div class="p-3 rounded-4 shadow bg-body-tertiary">
            <div class="btn-group-vertical w-100">
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'index.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>"><i class="bi bi-house-fill"></i> Home</a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'image.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/image.php?artworkid=<?php echo $_GET['id']; ?>"><i class="bi bi-eye-fill"></i> <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'index.php' && basename(dirname($_SERVER['PHP_SELF'])) == 'edit') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'index.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-pencil-fill"></i> Edit <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'upload.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/upload.php?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'upload.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-cloud-arrow-up-fill"></i> Upload new images to <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'all.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/all.php?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'all.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-images"></i> All images from <?php echo $image['title']; ?></a>
            </div>
          </div>
        </div>
        <div class="d-md-none d-lg-none">
          <a class="btn bg-secondary p-3 bg-opacity-25 fw-bold w-100 text-start" data-bs-toggle="collapse" href="#collapseModal" role="button" aria-expanded="false" aria-controls="collapseExample">
            <i class="bi bi-list" style="-webkit-text-stroke: 1px;"></i> Menu
          </a>
          <div class="collapse bg-secondary bg-opacity-25 mt-2 rounded" id="collapseModal">
            <div class="btn-group-vertical w-100">
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'index.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>"><i class="bi bi-house-fill"></i> Home</a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'image.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/image.php?artworkid=<?php echo $_GET['id']; ?>"><i class="bi bi-eye-fill"></i> <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'index.php' && basename(dirname($_SERVER['PHP_SELF'])) == 'edit') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'index.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-pencil-fill"></i> Edit <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'upload.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/upload.php?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'upload.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-cloud-arrow-up-fill"></i> Upload new images to <?php echo $image['title']; ?></a>
              <a class="btn py-2 rounded text-start link-body-emphasis <?php if(basename($_SERVER['PHP_SELF']) == 'all.php') echo 'fw-bold'; else echo 'fw-medium'; ?>" href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']; ?>/edit/all.php?id=<?php echo $_GET['id']; ?>"><?php if(basename($_SERVER['PHP_SELF']) == 'all.php') echo '<i class="bi bi-chevron-right small" style="-webkit-text-stroke: 2px;"></i>' ?> <i class="bi bi-images"></i> All images from <?php echo $image['title']; ?></a>
            </div>
          </div>
        </div>
      </nav>